EXLM-55 MD converter for video
adobe-experience-league/exlm-converter pull request #1
Opened 2023-10-04 13:00 UTC by ruhisingh1

2023-10-04 14:43 UTC, ahmed-musallam commented
very small 2 changes requested, otherwise LGTM! feel free to merge

2023-10-04 15:05 UTC, ahmed-musallam requested changes

2023-10-04 16:11 UTC, ruhisingh1 commented on src/modules/ExlMd2Html.js
> +  const htmlForDomTrasnsformation =  toHtml(hast, {
Fixed

2023-10-04 16:11 UTC, ruhisingh1 commented on src/modules/blocks/create-video.js
> +        p2.innerHTML = '<a href="' + href + '">' + href + '</a>';
Fixed

2023-10-04 16:12 UTC, ruhisingh1 reviewed
Addressed review comments.

2023-10-04 17:39 UTC, ahmed-musallam commented
LGTM. please merge

2023-10-04 17:39 UTC, ahmed-musallam approved these changes

2023-10-05 09:38 UTC, tprasad05 approved these changes

2023-10-05 09:38 UTC, merged