EXLM-94: exl table converter
adobe-experience-league/exlm-converter pull request #11
Opened 2023-10-10 00:41 UTC by gandal-adobe

EXLM-94: add table converter.
Change from h('main', [h('div', content.hast)]) to  h('main', content.hast) is needed as that extra nested DIV seem to confuse the hlx pipeline and produce very different results - <p> elements instead of table block.

2023-10-10 09:29 UTC, Sivaramvt commented on src/modules/ExlMd2Html.js
> +      h('main', content.hast),
I see that this div is anyway stripped out in the franlin output. Danaher project too follow this structure.

https://github.com/hlxsites/danaher-ls-aem/blob/7c3ed992c522da25a0f6d5dd94a9f33a2e6aecf2/tools/actions/convert/src/modules/md2html.js#L57

2023-10-10 09:32 UTC, Sivaramvt submitted a review, later dismissed

2023-10-10 10:17 UTC, Sivaramvt commented on src/modules/ExlMd2Html.js
> +      h('main', content.hast),
However, doing this resulting in content loss (half the markup is lost when it's out of franklin).
We have to be little cautious about this change I guess
https://258616-518tealdonkey.adobeioruntime.net/api/v1/web/main/convert/docs/authoring-guide-exl/using/markdown/cheatsheet
https://main--exlm--sivaramvt.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet

2023-10-11 01:52 UTC, ahmed-musallam requested changes
This is no longer needed because of #13

2023-10-11 05:35 UTC, ahmed-musallam commented
Closing this as it is no longer needed. see #13

2023-10-11 11:15 UTC, closed without merging